kind = "web"
previewPath = "/"
title = "Carper Tienda"
version = "1.0.0"
id = "artifacts/tienda"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22179

[services.development]
run = "pnpm --filter @workspace/tienda run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tienda", "run", "build" ]
publicDir = "artifacts/tienda/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22179"
BASE_PATH = "/"
