uploads = []
outputs = []

[[generated]]
id = "rL174yP_avd4V9fDfGMmb"
uri = "file://artifacts/mockup-sandbox/public/carper-alternator.png"
type = "image"
title = "Alternator auto part"

[[generated]]
id = "oHVlTXvNBhWJQt9q7rxjR"
uri = "file://artifacts/mockup-sandbox/public/carper-starter.png"
type = "image"
title = "Starter motor auto part"

[[generated]]
id = "ct5Opmf58rbnp8oM7lQL3"
uri = "file://artifacts/carper/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hcKFrEIC88yIeT4fUIKw0"
uri = "file://artifacts/carper/assets/images/ofertas/01-joyas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "crWV0snVPXIzDtB1fJdFl"
uri = "file://artifacts/carper/assets/images/ofertas/02-deldia.png"
type = "image"
title = "generated_image"

[[generated]]
id = "dMMtGb6OTE7Bj-_nBlhby"
uri = "file://artifacts/carper/assets/images/ofertas/03-noarranca.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZRXS1KjlTioSxZhm1360q"
uri = "file://artifacts/carper/assets/images/ofertas/04-despiece.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mQ4Ksx-_kjoTeJod_y795"
uri = "file://artifacts/carper/assets/images/ofertas/05-checkengine.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FBnbDnT3PlMUGUtbW__Hw"
uri = "file://artifacts/carper/assets/images/ofertas/06-bombas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SPxx6OgNHv_2Zy2cDSahH"
uri = "file://artifacts/carper/assets/images/ofertas/07-carbuclean.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Re9FUi-Gw6FIzGfhv9e0J"
uri = "file://artifacts/carper/assets/images/ofertas/08-sensores.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eaAGroSLFRT81bQ7njJ2T"
uri = "file://artifacts/carper/assets/images/ofertas/09-bobinas.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gQo4Fk-IbUUcMzITloJ9H"
uri = "file://artifacts/carper/assets/images/ofertas/10-restock.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2gPIBO8GHpgV-jSd7NQFX"
uri = "file://artifacts/carper/assets/images/tips/alternador.png"
type = "image"
title = "alternator tip"

[[generated]]
id = "x3TUPaV8H5PmHCHuEzmwV"
uri = "file://artifacts/carper/assets/images/tips/bomba.png"
type = "image"
title = "fuel pump tip"

[[generated]]
id = "eXkGMumLrk1CyBeKOHrAf"
uri = "file://artifacts/carper/assets/images/tips/afinacion.png"
type = "image"
title = "tune up tip"
