// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carper-a/Inicio.tsx": () => import("../components/mockups/carper-a/Inicio.tsx"),
  "./components/mockups/carper-a/Producto.tsx": () => import("../components/mockups/carper-a/Producto.tsx"),
  "./components/mockups/carper-a/Resultados.tsx": () => import("../components/mockups/carper-a/Resultados.tsx"),
  "./components/mockups/carper-b/Inicio.tsx": () => import("../components/mockups/carper-b/Inicio.tsx"),
  "./components/mockups/carper-b/Producto.tsx": () => import("../components/mockups/carper-b/Producto.tsx"),
  "./components/mockups/carper-b/Resultados.tsx": () => import("../components/mockups/carper-b/Resultados.tsx")
};
